backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true # for local git repo development
publish_mode: editorial_workflow # allow drafts
media_folder: /public/img/uploads # where to save uploaded files in repo
public_folder: /public/img/uploads # where uploaded files are found in published site; defaults to media_folder if not existing 
collections:
  - name: "projects"
    label: "Projects"
    folder: "/pages/projects"
    create: true # allow creation of new projects
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Date", name: "date", widget: "datetime"}
    - {label: "Image", name: "thumbnail", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}