name: testing
on: push
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm test:unit
  e2e:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm astro build
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: pnpm preview
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:4321'